server:
  port: 9092

spring:
  application:
    name: travel-billing-system-java
  datasource:
    url: jdbc:mysql://localhost:3306/travelbillingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: ${GEMINI_API_KEY:}
