package com.travelbilling.service;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.travelbilling.entity.Bill;
import com.travelbilling.repository.BillRepository;
import com.travelbilling.util.NumberToWordsUtil;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class PdfService {
    private final BillRepository billRepository;
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy");

    public byte[] generateInvoicePdf(Long billId) {
        Bill bill = billRepository.findById(billId)
                .orElseThrow(() -> new IllegalArgumentException("Bill not found"));

        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf, PageSize.A4);
            document.setMargins(20, 20, 20, 20);

            // Header
            document.add(new Paragraph("Sri Tulja Bhavani Travels")
                    .setFontSize(24)
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(5));
            document.add(new Paragraph("Professional Travel Solutions")
                    .setFontSize(10)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20));

            // Invoice Info Table
            Table infoTable = new Table(UnitValue.createPercentArray(new float[]{50, 50}))
                    .useAllAvailableWidth()
                    .setMarginBottom(20);

            infoTable.addCell(createLabelValueCell("Bill Number:", bill.getBillNumber()));
            infoTable.addCell(createLabelValueCell("Bill Date:", bill.getBillDate().format(DATE_FORMATTER)));
            infoTable.addCell(createLabelValueCell("Customer:", bill.getCompanyName()));
            infoTable.addCell(createLabelValueCell("Vehicle:", bill.getVehicleName()));
            infoTable.addCell(createLabelValueCell("Duty Slip No:", bill.getDutySlipNo()));
            infoTable.addCell(createLabelValueCell("KMs:", String.valueOf(bill.getTotalKms())));
            infoTable.addCell(createLabelValueCell("Hours:", String.valueOf(bill.getTotalHours())));
            infoTable.addCell(new Cell()); // Empty cell to fill

            document.add(infoTable);

            // Charges Table
            Table chargesTable = new Table(UnitValue.createPercentArray(new float[]{70, 30}))
                    .useAllAvailableWidth()
                    .setMarginBottom(20);

            chargesTable.addHeaderCell(new Cell().add(new Paragraph("Description").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));
            chargesTable.addHeaderCell(new Cell().add(new Paragraph("Amount (INR)").setBold()).setBackgroundColor(ColorConstants.LIGHT_GRAY));

            addChargeRow(chargesTable, "Base Amount", bill.getBaseAmount());
            addChargeRow(chargesTable, "Driver Bata", bill.getDriverBata());
            addChargeRow(chargesTable, "Parking Charges", bill.getParking());
            addChargeRow(chargesTable, "Toll Charges", bill.getToll());
            addChargeRow(chargesTable, "Night Charges", bill.getNightCharges());
            addChargeRow(chargesTable, "Other Charges", bill.getOtherCharges());

            // Grand Total Row
            chargesTable.addCell(new Cell().add(new Paragraph("Grand Total").setBold()).setTextAlignment(TextAlignment.RIGHT));
            chargesTable.addCell(new Cell().add(new Paragraph(String.format("%.2f", bill.getGrandTotal())).setBold()));

            document.add(chargesTable);

            // Rupees in words
            document.add(new Paragraph("Amount in words: " + NumberToWordsUtil.convertToRupees(bill.getGrandTotal()))
                    .setFontSize(10)
                    .setItalic()
                    .setMarginBottom(20));

            // Created By
            document.add(new Paragraph("Generated by: " + bill.getCreatedBy())
                    .setFontSize(8)
                    .setMarginBottom(40));

            // Footer / Signature
            Table footerTable = new Table(UnitValue.createPercentArray(new float[]{100}))
                    .useAllAvailableWidth();
            footerTable.addCell(new Cell()
                    .add(new Paragraph("Authorized Signature")
                            .setBold()
                            .setTextAlignment(TextAlignment.RIGHT))
                    .setBorder(com.itextpdf.layout.borders.Border.NO_BORDER));
            
            document.add(footerTable);

            document.close();
        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF", e);
        }

        return out.toByteArray();
    }

    private Cell createLabelValueCell(String label, String value) {
        Paragraph p = new Paragraph()
                .add(new com.itextpdf.layout.element.Text(label).setBold())
                .add(" " + (value != null ? value : "-"));
        return new Cell().add(p).setBorder(com.itextpdf.layout.borders.Border.NO_BORDER);
    }

    private void addChargeRow(Table table, String description, Double amount) {
        table.addCell(new Cell().add(new Paragraph(description)));
        table.addCell(new Cell().add(new Paragraph(String.format("%.2f", amount != null ? amount : 0.0))));
    }
}
